Textconverter/Textconverter/urls.py
from django.contrib import admin
from django.urls import path
from web import views
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.users, name="link_name"),
    path('',views.index, name="index"),
    path('web/',include('web.urls')),


]

Textconverter/web/urls.py
from django.urls import path
from . import views

# SET THE NAMESPACE!
app_name = 'web'

urlpatterns=[

    path('about/',views.about,name='about'),
]

Textconverter/web/models.py
from django.db import models

# Create your models here.
class Link(models.Model):
    URL_of_website = models.URLField(unique=False)
    Number_of_Lines = models.PositiveIntegerField(default=5)

    def __str__(self):
        return self.URL_of_website

Textconverter/web/forms.py
from django import forms
from web.models import Link

class NewLink(forms.ModelForm):
    class Meta():
        model = Link
        fields ='__all__'




# class NumLink(forms.ModelForm):
#     class Meta():
#         model = Link
#         fields =(Num_OF_Line)

Textconverter/web/views.py
from django.shortcuts import render
from . import models
from web.forms import NewLink

import bs4 as bs
import urllib.request
import re
import pandas as pd
import heapq
import nltk
from web.models import Link
import lxml.etree
import lxml
import requests




# Create your views here.




def users(request):
    form = NewLink()



    if request.method == "POST":
        form = NewLink(request.POST)



        if form.is_valid() :
            form.save(commit=True)




            return index(request)
        else:
            print("Error Form Invalid")
    return render(request,'link_name.html', {'form':form})







def index(request):
    field_name = 'Number_of_Lines'
    obj = Link.objects.last()
    field_object = Link._meta.get_field(field_name)
    ho = field_object.value_from_object(obj)




    so = Link.objects.all().last()
    # so = ho.objects.all()





    url_list = [so]
    for url in url_list:#this means go to each url
        response = requests.get(url)#this is where we are accessing programatically the url, this is basiclly scrapping
        xml_page = response.text#get the text inside it



    #source =urllib.request.urlopen(ho).read()
    soup = bs.BeautifulSoup(xml_page,'lxml')
    text = ""
    for paragraph in soup.find_all('p'):#soup is object which contain all html, here we are telling find all p tag
        print(paragraph.text)#paragraph is actually a tag , so we cannot concat it with string that's why we are using .text to convert it into string
        text += paragraph.text
        text += '\n\n'
    text = re.sub(r'\[[0-9]*\]',' ',text)
    text = re.sub(r'\s+',' ',text)
    clean_text = text.lower()
    clean_text = re.sub(r'\W',' ',clean_text)#if any word character is there (-- _ -+) replace it with space
    clean_text = re.sub(r'\d',' ',clean_text)#if there is single digit replace it with space
    clean_text = re.sub(r'\s+',' ',clean_text)
    sentences = nltk.sent_tokenize(text)#ham sentence ko tokenize kr rahe hai
    stop_words = nltk.corpus.stopwords.words('english')
    word2count = {}#create a dictionary object
    for word in nltk.word_tokenize(clean_text):#we go to the text which we have clean
        if word not in stop_words:
            if word not in word2count.keys():
                word2count[word] = 1
            else:
                word2count[word] += 1
    for key in word2count.keys():
        word2count[key] = word2count[key]/max(word2count.values())
    sent2score = {}
    for sentence in sentences:
        for word in nltk.word_tokenize(sentence.lower()):
            if word in word2count.keys():
                if len(sentence.split(' ')) < 25:#IF sentence has more than 25 words you don't considered it
                    if sentence not in sent2score.keys():
                        sent2score[sentence] = word2count[word]
                    else:
                        sent2score[sentence] += word2count[word]

# Gettings best 5 lines
    best_sentences = heapq.nlargest(ho, sent2score, key=sent2score.get)
    text =""

    for sentence in best_sentences:
        text=text+sentence


    my_dict = {'insert_me':text}
    return render(request,'index.html',context=my_dict)



def about(request):
    return render(request,'about.html')





#
# class LinkDetailView(DetailView):
#     context_object_name= 'link_detail'
#     model=models.Link
#
#
#     template_name = 'web/index.html'
#     def get_context_data(self,**kwargs):
#         context  = super(LinkDetailView,self).get_context_data(**kwargs)
#
#         return context

Textconverter/web/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  </head>

  <body>

  </nav>
    <div class="container">
      <div class="jumbotron">
        <h1>The Interesing Company</h1>
        <p></p>
        <p></p>
        <p></p>
        <p></p>
        <p></p>
        <p></p>
        <p></p>
        <h3>This is an AI based application which is developed <em>by Rishabh Gupta</em></h3>
        <p>Hey , what you saw there, that is not a cool that is Super cool </p>
        <p>This is the power of Machine learning and Natural Language Processing</p>







      </div>

    </div>

  </body>
</html>

Textconverter/web/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {# Custom CSS#}
    <link rel="stylesheet" href="{% static 'css/two.css' %}">
  </head>
  <body class="yo">
    <div class="container">
      <div class="jumbotron">
        <h1>Here is your summary !</h1>
        <p></p>
        <p></p>
        <p></p>
        <p>
        </p>
        <p></p>
        <p></p>
        <p></p>
        <p></p>
        <p> {{ insert_me }} </p>


      </div>

    </div>


  </body>
</html>

Textconverter/web/templates/link_name.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Linksite</title>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
      {# Custom CSS#}
      <link rel="stylesheet" href="{% static 'css/mycss.css' %}">

      {# Fonts#}
      <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">
    </head>
  </head>
  <body class="loader">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark techfont">

      <a class="navbar-brand" href="#">The Intersting Company</a>

      <!-- Brand and toggle get grouped for better mobile display -->
      <!-- This is the actual code that creates the "hamburger icon" -->
      <!-- The data-target grabs ids to put into the icon -->
      <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="bs-example-navbar-collapse-1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>


      <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
      <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> --> -->
        <div class="navbar-nav">

          <!-- the span class "sr-only" tells screen readers that Home is the active link, for accessibility -->

          <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url 'web:about' %}">About us</a>





          <!-- SEARCH BAR -->
          <!-- <form class="form-inline"> -->
            <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline my-2 my-sm-0" type="submit">Submit</button>
          </form> -->

        </div> <!-- /.navbar-nav, left-hand content -->

        <!-- STUFF ON THE RIGHT -->

        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="https://en.wikipedia.org/wiki/India">Contact us</a>
          <a class="nav-item nav-link" href="https://github.com/">GitHub</a>

        </div> <!-- /.navbar-nav, right-hand content -->


      </div> <!-- /.navbar-collapse -->
    </nav>
    <div class="container">
      <h1 class="jay">We convert Long Text into Summary</h1>


      <div class="jumbotron">
        <h1 class="Yellow">Welcome, please provide the url</h1>
        <p>type the url of any text content based website </p>
        <p>like wikipedia,ex: https://en.wikipedia.org/wiki/Light_pollution </p>
          <p></p>
          <p></p>
          <p></p>
          <p></p>
        <form  class="hello" enctype="multipart/form-data" method="post">
          {% csrf_token %}
          {{ form.as_p }}


          <input class="loading" type="Submit"  value="Get Summary">

        </form>

      </div>

    </div>




    <script src="{% static "js/myjs.js"%}" type="text/javascript" ></script>

  </body>
</html>